### ISSUE TITLE
which shadow is doing this cohort?

### ISSUE THREAD

**Issue by cclatterbuck** [Openscapes/github-clinic#4]
There are two cohorts, we haven't decided who is shadowing what cohort yet. @AHolder1 any ideas?

**Comment by erinmr** [comment]
both are going to be great!

**Comment by AHolder1** [comment]
@cclatterbuck - Not sure, virtual thumb war to decide?

**Comment by jules32** [comment]
Hi @cclatterbuck @AHolder1 @erinmr , 

Love seeing all your issues from last week, nice work!

How about: 

- Anna joins the NWFSC cohort, @ 11-12:30 PT
- Corey joins the FDD cohort, @ 9-10:30 PT

What do you think?

**Comment by AHolder1** [comment]
Good morning @jules32 @cclatterbuck @erinmr !

That plan works for me!

**Comment by cclatterbuck** [comment]
Hi all -- I would love the opportunity to connect with NWFSC if possible. I went ahead and accepted this the NWFSC series on my calendar so I'll go ahead and close the issue. Thanks for your thoughtfulness!
